
library(MASS)
library(dplyr)
library(tidyr)
library(nnet)

data <- read.csv("/content/sample_data/click_project.csv")

data$age <- factor(data$age)
data$gender <- factor(data$gender)
data$educ_choice <- factor(data$educ_choice)
data$lit_genres_choice <- factor(data$lit_genres_choice)
data$movie_genres_choice <- factor(data$movie_genres_choice)
data$is_cb <- factor(data$is_cb)
data$is_descr <- factor(data$is_descr)
data$is_mystery <- factor(data$is_mystery)
data$is_documentary <- factor(data$is_documentary)
data$emotion_choice <- factor(data$emotion_choice)
data$topic <- factor(data$topic)

likert_vars <- c("clickability", "interest", "familiarity", "credibility")
data[likert_vars] <- lapply(data[likert_vars], function(x) factor(x, ordered = TRUE))

model_click1 <- polr(clickability ~ is_cb, data = data, Hess = TRUE)
summary(model_click1)
model_click2 <- polr(clickability ~ topic, data = data, Hess = TRUE)
summary(model_click2)
model_click3 <- polr(clickability ~ is_mystery, data = data, Hess = TRUE)
summary(model_click3)
model_click4 <- polr(clickability ~ is_documentary, data = data, Hess = TRUE)
summary(model_click4)
model_click5 <- polr(clickability ~ emotion_choice, data = data, Hess = TRUE)
summary(model_click5)
model_click6 <- polr(interest ~ is_cb, data = data, Hess = TRUE)
summary(model_click6)
model_click7 <- polr(familiarity ~ is_cb, data = data, Hess = TRUE)
summary(model_click7)
model_click8 <- polr(credibility ~ is_cb, data = data, Hess = TRUE)
summary(model_click8)
model_click9 <- polr(interest ~ topic, data = data, Hess = TRUE)
summary(model_click9)
model_click10 <- polr(familiarity ~ topic, data = data, Hess = TRUE)
summary(model_click10)
model_click11 <- polr(credibility ~ topic, data = data, Hess = TRUE)
summary(model_click11)
model_click12 <- multinom(emotion_choice ~ is_cb, data=data, Hess=TRUE)
summary(model_click12)
model_click13 <- polr(clickability ~ familiarity, data = data, Hess = TRUE)
summary(model_click13)
model_click14 <- polr(clickability ~ age, data = data, Hess = TRUE)
summary(model_click14)
model_click15 <- polr(clickability ~ gender, data = data, Hess = TRUE)
summary(model_click15)
model_click16 <- polr(clickability ~ educ_choice, data = data, Hess = TRUE)
summary(model_click16)
